# Generated by Django 5.1.1 on 2024-09-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="Почта"
                    ),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                ("street", models.CharField(max_length=50, verbose_name="Улица")),
                (
                    "house_number",
                    models.PositiveSmallIntegerField(verbose_name="Номер дома"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Наименование"),
                ),
                (
                    "product_model",
                    models.CharField(max_length=250, verbose_name="Модель"),
                ),
                (
                    "release_date",
                    models.DateField(verbose_name="Дата выхода продукта на рынок"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="HierarchyElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название звена иерархии"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "hierarchy_type",
                    models.CharField(
                        choices=[
                            ("factory", "завод"),
                            ("retail network", "розничная сеть"),
                            (
                                "individual entrepreneur",
                                "индивидуальный предприниматель",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Тип звена иерархии",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0, verbose_name="Уровень звена иерархии"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail_chain.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail_chain.hierarchyelement",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retail_chain.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент иерархии",
                "verbose_name_plural": "Элементы иерархии",
            },
        ),
    ]
