# Generated by Django 5.1.1 on 2024-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_chain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hierarchyelement",
            name="country",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
