# Generated by Django 5.1.1 on 2024-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_chain", "0002_hierarchyelement_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="hierarchyelement",
            name="city",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="Город"
            ),
        ),
    ]
